name: tharkyApp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.5+5
version: 2.2.0+20

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_code_picker: ^3.0.0
  flutter_facebook_auth: ^6.0.4
  pin_code_fields: ^8.0.1
  #swipe_stack: 1.0.0
  #flutter_swiper: 1.1.6
  #geocoder: 0.2.1
  geocoding: ^3.0.0
  flutter_swiper_null_safety: ^1.0.2
  get: ^4.6.6
  #swipable_stack: ^0.5.0

  intl: 0.19.0
  # geolocator: ^6.1.13
  location: ^7.0.1
  image_picker: ^1.1.2
  image_cropper: ^4.0.1
  flutter_video_info: ^1.3.2
  video_player: ^2.9.2
  #ffmpeg_kit_flutter_full: ^6.0.3
  animate_do: ^3.3.7

  path_provider: ^2.0.14
  cached_network_image: ^3.2.3
  share: ^2.0.4
  #flutter_webview_plugin: ^0.4.0
  logger: ^2.5.0
  in_app_purchase: ^3.1.5
  rflutter_alert: ^2.0.4
  permission_handler: ^11.3.1
  flutter_ringtone_player: ^4.0.0+3
  shimmer: ^3.0.0
  #apple_sign_in: ^0.1.0
  url_launcher: ^6.1.10
  flutter_mapbox_autocomplete:  ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.1
  google_mobile_ads: ^5.2.0
  nb_utils: ^6.0.7
  mobx: ^2.5.0
  html: ^0.15.5
  flutter_custom_tabs: ^2.1.0
  flutter_mobx: ^2.3.0
  flutter_styled_toast: ^2.2.1
  sliding_up_panel: ^2.0.0+1
  flutter_map:
  socket_io_client: ^1.0.2
  flutter_local_notifications: ^18.0.1
  flutter_webrtc: ^0.12.11
  just_audio: ^0.9.46
  sdp_transform: ^0.3.2
  faker: ^2.2.0
  webview_flutter: ^4.2.2
#  webview_flutter: ^4.10.0
  change_app_package_name: ^1.5.0
  video_thumbnail: ^0.5.6
  mask_text_input_formatter: ^2.9.0
  http: ^0.13.6
  shared_preferences: ^2.3.3
  flutter_inappwebview: ^5.7.2+3
  uni_links: ^0.5.1
  camera: ^0.11.2
  google_mlkit_face_detection: ^0.13.1
  tflite_flutter: ^0.11.0
  image: ^4.2.0
  external_app_launcher: ^4.0.3
  android_intent_plus: ^6.0.0
  screenshot: ^3.0.0
  share_plus: ^7.2.2
  flutter_mailer: ^3.0.1
#  flutter_email_sender:
#  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.4.6
  mobx_codegen: ^2.7.0


flutter_icons:
  android: true
  ios: true
  image_path: "asset/icons/icon2.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/ml/age_model.tflite
    - asset/auth/
    - asset/
    - asset/translation/
    - asset/icons/
    - asset/
