//
// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// //import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:firebase_core/firebase_core.dart';
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCzTwfpM-AOhLQycNMGJJpb7J0KaDWERuY',
//     appId: '1:526130031974:web:1f6b806a24385408d6aca7',
//     messagingSenderId: '526130031974',
//     projectId: 'roar-magic',
//     authDomain: 'roar-magic.firebaseapp.com',
//     storageBucket: 'roar-magic.firebasestorage.app',
//     measurementId: 'G-PD917YT68Q',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBoWb80nPEWZODlqMtDEqRonJ_pcK0YUR8',
//     appId: '1:526130031974:android:52905ad830b5a26bd6aca7',
//     messagingSenderId: '526130031974',
//     projectId: 'roar-magic',
//     storageBucket: 'roar-magic.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyC6jL8fquOmT9br5FZ7Q-Ka2Wi9AGhbGeE',
//     appId: '1:526130031974:ios:8104290ab5c4f4a2d6aca7',
//     messagingSenderId: '526130031974',
//     projectId: 'roar-magic',
//     storageBucket: 'roar-magic.firebasestorage.app',
//     iosBundleId: 'com.deligence.hookup4u',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyC6jL8fquOmT9br5FZ7Q-Ka2Wi9AGhbGeE',
//     appId: '1:526130031974:ios:e2342840bc6fe3bad6aca7',
//     messagingSenderId: '526130031974',
//     projectId: 'roar-magic',
//     storageBucket: 'roar-magic.firebasestorage.app',
//     iosBundleId: 'com.roar.magic',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCzTwfpM-AOhLQycNMGJJpb7J0KaDWERuY',
//     appId: '1:526130031974:web:8def4b063c2aff59d6aca7',
//     messagingSenderId: '526130031974',
//     projectId: 'roar-magic',
//     authDomain: 'roar-magic.firebaseapp.com',
//     storageBucket: 'roar-magic.firebasestorage.app',
//     measurementId: 'G-3N6J1SNFLN',
//   );
// }
// */
